name: Complete CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml

  notify:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - run: echo "✅ Full pipeline completed successfully!"
