name: Complete CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml
    secrets: inherit

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml
    secrets: inherit
