name: Complete Pipeline (Backend + Frontend)

on:
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml
    with:
      product_api_ip: ${{ needs.backend.outputs.PRODUCT_API_IP }}
      order_api_ip: ${{ needs.backend.outputs.ORDER_API_IP }}
