name: Complete CI/CD - Backend + Frontend

on:
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml

  frontend:
    uses: ./.github/workflows/frontend-pipeline.yml
    needs: backend
#triggering the backend with this comment





