name: Complete CI/CD - Backend + Frontend

on:
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml
