name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-pipeline.yml"
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: tejaacr98765.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & Push Frontend
        run: |
          az acr login --name tejaacr98765
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      - name: Deploy Frontend
        run: |
          az aks get-credentials --resource-group rg-teja --name aks-teja --overwrite-existing
          kubectl apply -f k8s/frontend.yaml
          kubectl set image deployment/frontend frontend-container=${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
