name: Frontend CI/CD - Build, Push and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pipeline.yml'

env:
  ACR_LOGIN_SERVER: tejaacr98765.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        run: az logout
        if: always()

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_and_push_frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context (AKS)
        run: |
          az aks get-credentials \
            --resource-group rg-teja \
            --name aks-teja \
            --overwrite-existing

      - name: Deploy Frontend Service
        run: |
          kubectl apply -f k8s/frontend.yaml
