name: Frontend CI/CD - Build, Push and Deploy
#triggering comment














###
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pipeline.yml'

env:
  ACR_LOGIN_SERVER: tejaacr98765.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_and_push_frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group rg-teja \
            --name aks-teja \
            --overwrite-existing

      - name: Deploy Frontend
        run: |
          cd k8s/
          kubectl apply -f frontend.yaml
